//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class hoadon
    {
        public hoadon() { }
        public hoadon(string mahoadon, string manv, string maphieuthue, string tongngaythue, string tongtienphong, string tongtiendichvu, string ngaythanhtoan)
        {
            this.mahoadon = mahoadon;
            this.manv = manv;
            this.maphieuthue = maphieuthue;
            this.tongngaythue = tongngaythue;
            this.tongtienphong = tongtienphong;
            this.tongtiendichvu = tongtiendichvu;
            this.ngaythanhtoan = ngaythanhtoan;
        }

        public string mahoadon { get; set; }
        public string manv { get; set; }
        public string maphieuthue { get; set; }
        public string tongngaythue { get; set; }
        public string tongtienphong { get; set; }
        public string tongtiendichvu { get; set; }
        public string ngaythanhtoan { get; set; }
    
        public virtual nhanvien nhanvien { get; set; }
        public virtual phieuthue phieuthue { get; set; }
    }
}
