//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class khachhang
    {
        public khachhang()
        {
            this.phieudats = new HashSet<phieudat>();
            this.phieuthues = new HashSet<phieuthue>();
        }

        public khachhang(string cmnd, string hoten, string dienthoai)
        {
            this.cmnd = cmnd;
            this.hoten = hoten;
            this.dienthoai = dienthoai;
        }

        public string cmnd { get; set; }
        public string hoten { get; set; }
        public string dienthoai { get; set; }
    
        public virtual ICollection<phieudat> phieudats { get; set; }
        public virtual ICollection<phieuthue> phieuthues { get; set; }
    }
}
