//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class nhanvien
    {
        public nhanvien()
        {
            this.hoadons = new HashSet<hoadon>();
            this.phieudats = new HashSet<phieudat>();
            this.phieuthues = new HashSet<phieuthue>();
            this.taikhoans = new HashSet<taikhoan>();
        }
    
        public string manv { get; set; }
        public string tennv { get; set; }
        public string dienthoai { get; set; }
        public string diachi { get; set; }
        public string email { get; set; }
    
        public virtual ICollection<hoadon> hoadons { get; set; }
        public virtual ICollection<phieudat> phieudats { get; set; }
        public virtual ICollection<phieuthue> phieuthues { get; set; }
        public virtual ICollection<taikhoan> taikhoans { get; set; }
    }
}
