//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLKSEntities : DbContext
    {
        public QLKSEntities()
            : base("name=QLKSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<dichvu> dichvus { get; set; }
        public DbSet<hoadon> hoadons { get; set; }
        public DbSet<khachhang> khachhangs { get; set; }
        public DbSet<nhanvien> nhanviens { get; set; }
        public DbSet<phieudat> phieudats { get; set; }
        public DbSet<phieuthue> phieuthues { get; set; }
        public DbSet<phong> phongs { get; set; }
        public DbSet<sudungdichvu> sudungdichvus { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<taikhoan> taikhoans { get; set; }
    }
}
