//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class sudungdichvu
    {
        public sudungdichvu() { }
        public sudungdichvu(int stt)
        {
            this.stt = stt;
        }
        public sudungdichvu(string maphieuthue, string tendichvu, string soluong, string tongtien)
        {
            this.maphieuthue = maphieuthue;
            this.tendichvu = tendichvu;
            this.soluong = soluong;
            this.tongtien = tongtien;
        }

        public int stt { get; set; }
        public string maphieuthue { get; set; }
        public string tendichvu { get; set; }
        public string soluong { get; set; }
        public string tongtien { get; set; }
    
        public virtual phieuthue phieuthue { get; set; }
    }
}
