//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class taikhoan
    {
        public string manv { get; set; }
        public string tentaikhoan { get; set; }
        public string matkhau { get; set; }
        public string chucvu { get; set; }
    
        public virtual nhanvien nhanvien { get; set; }
    }
}
