//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiBanHang.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ct_PhieuNhap
    {
        public int id { get; set; }
        public string mapn { get; set; }
        public string mahang { get; set; }
        public decimal soluong { get; set; }
        public decimal gianhap { get; set; }
        public decimal thanhtien { get; set; }
    
        public virtual HangHoa HangHoa { get; set; }
        public virtual PhieuNhap PhieuNhap { get; set; }
    }
}
