//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiBanHang.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HangHoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HangHoa()
        {
            this.Ct_HoaDon = new HashSet<Ct_HoaDon>();
            this.Ct_PhieuNhap = new HashSet<Ct_PhieuNhap>();
        }
    
        public string mahang { get; set; }
        public string tenhang { get; set; }
        public string hangsx { get; set; }
        public Nullable<decimal> soluong { get; set; }
        public Nullable<decimal> dongia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ct_HoaDon> Ct_HoaDon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ct_PhieuNhap> Ct_PhieuNhap { get; set; }
    }
}
